package com.kakaobean.core.notification.domain;


public enum NotificationType {
    RELEASE_NOTE_DEPLOYMENT,
    TASK,
    POSTED_COMMENT,
    FINISHED_WRITING_RELEASE_NOTE,
    REGISTER_MANUSCRIPT,
    MODIFIED_PROJECT_MEMBER_ROLE,
    MODIFIED_MANUSCRIPT,
    START_MANUSCRIPT_MODIFICATION;
}
