name: Deploy

on: 
  push:
    branches: [ "main" ]

env:
  S3_BUCKET_NAME: coconote
  PROJECT_NAME: coconote

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      # api 모듈 관련 yml 생성
      - name: Make api main yml
        run: |
          cd ./api/src/main/resources
          touch ./application.yml
          echo "${{ secrets.API_APPLICATION_YML }}" > ./application.yml
        shell: bash

      # core 모듈 관련 yml 생성
      - name: Make core main yml
        run: |
          cd ./core/src/main/resources
          touch ./application-core.yml
          echo "${{ secrets.CORE_MAIN_APPLICATION_YML }}" >> ./application-core.yml
        shell: bash

      - name: Make core test yml
        run: |
          cd ./core/src/test/resources
          touch ./application.yml
          echo "${{ secrets.CORE_TEST_APPLICATION_YML }}" >> ./application.yml
        shell: bash

      # independently-system 모듈 관련 yml 생성
      - name: Make indepenently-system main yml
        run: |
          cd ./independently-system/src/main/resources
          touch ./application-independently-system.yml
          echo "${{ secrets.INDEPENDENTLY_MAIN_APPLICATION_YML }}" >> ./application-independently-system.yml
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
      
      - name: BootJar
        run: ./gradlew bootjar
        shell: bash
        
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{ secrets.S3_BUCKET_NAME }}/$PROJECT_NAME/$GITHUB_SHA.zip
